name: .NET Core Tests

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest # Обязательно для WPF

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x # Убедись, что это совпадает с твоим проектом!

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
